import { ItemDefinition, ItemCategory } from '@/types';

export const ITEM_LIBRARY: ItemDefinition[] = [
  // ── Structure ─────────────────────────────────────────────────────────────
  {
    type: 'plot-boundary',
    name: 'Plot Boundary',
    category: 'structure',
    defaultWidth: 40,
    defaultHeight: 30,
    color: '#1e293b',
    icon: '⬛',
    resizable: true,
    description: 'Outer plot boundary',
  },
  {
    type: 'wall',
    name: 'Wall',
    category: 'structure',
    defaultWidth: 10,
    defaultHeight: 1,
    color: '#374151',
    icon: '▬',
    resizable: true,
    description: 'Interior or exterior wall segment',
  },
  {
    type: 'column',
    name: 'Column / Pillar',
    category: 'structure',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#6b7280',
    icon: '⬜',
    resizable: false,
    description: 'Structural column or pillar',
  },

  // ── Rooms ─────────────────────────────────────────────────────────────────
  {
    type: 'room',
    name: 'Room',
    category: 'rooms',
    defaultWidth: 12,
    defaultHeight: 10,
    color: '#dbeafe',
    icon: '🏠',
    resizable: true,
    description: 'Generic room (12×10 ft)',
  },
  {
    type: 'master-bedroom',
    name: 'Master Bedroom',
    category: 'rooms',
    defaultWidth: 14,
    defaultHeight: 12,
    color: '#ede9fe',
    icon: '🛏️',
    resizable: true,
    description: 'Master bedroom (14×12 ft)',
  },
  {
    type: 'bedroom',
    name: 'Bedroom',
    category: 'rooms',
    defaultWidth: 12,
    defaultHeight: 10,
    color: '#fce7f3',
    icon: '🛏️',
    resizable: true,
    description: 'Standard bedroom (12×10 ft)',
  },
  {
    type: 'kids-room',
    name: "Kids' Room",
    category: 'rooms',
    defaultWidth: 10,
    defaultHeight: 10,
    color: '#dcfce7',
    icon: '🧸',
    resizable: true,
    description: "Children's room (10×10 ft)",
  },
  {
    type: 'guest-room',
    name: 'Guest Room',
    category: 'rooms',
    defaultWidth: 11,
    defaultHeight: 10,
    color: '#fff7ed',
    icon: '🛏️',
    resizable: true,
    description: 'Guest bedroom (11×10 ft)',
  },
  {
    type: 'living-room',
    name: 'Living Room',
    category: 'rooms',
    defaultWidth: 18,
    defaultHeight: 14,
    color: '#fef9c3',
    icon: '🛋️',
    resizable: true,
    description: 'Living/drawing room (18×14 ft)',
  },
  {
    type: 'drawing-room',
    name: 'Drawing Room',
    category: 'rooms',
    defaultWidth: 16,
    defaultHeight: 12,
    color: '#fef3c7',
    icon: '🖼️',
    resizable: true,
    description: 'Formal drawing room (16×12 ft)',
  },
  {
    type: 'study',
    name: 'Study / Office',
    category: 'rooms',
    defaultWidth: 10,
    defaultHeight: 10,
    color: '#e0f2fe',
    icon: '📚',
    resizable: true,
    description: 'Home study or office (10×10 ft)',
  },
  {
    type: 'prayer-room',
    name: 'Prayer Room',
    category: 'rooms',
    defaultWidth: 8,
    defaultHeight: 8,
    color: '#f0fdf4',
    icon: '🕌',
    resizable: true,
    description: 'Prayer / Namaz room (8×8 ft)',
  },
  {
    type: 'store-room',
    name: 'Store Room',
    category: 'rooms',
    defaultWidth: 8,
    defaultHeight: 6,
    color: '#fdf4ff',
    icon: '📦',
    resizable: true,
    description: 'Storage / utility room (8×6 ft)',
  },

  // ── Doors ─────────────────────────────────────────────────────────────────
  {
    type: 'main-door',
    name: 'Main Entrance Door',
    category: 'doors',
    defaultWidth: 4,
    defaultHeight: 1,
    color: '#92400e',
    icon: '🚪',
    resizable: false,
    description: 'Main front door (4 ft wide)',
  },
  {
    type: 'single-door',
    name: 'Single Door',
    category: 'doors',
    defaultWidth: 3,
    defaultHeight: 1,
    color: '#b45309',
    icon: '🚪',
    resizable: false,
    description: 'Standard single door (3 ft wide)',
  },
  {
    type: 'double-door',
    name: 'Double Door',
    category: 'doors',
    defaultWidth: 5,
    defaultHeight: 1,
    color: '#a16207',
    icon: '🚪',
    resizable: false,
    description: 'Double swing door (5 ft wide)',
  },
  {
    type: 'sliding-door',
    name: 'Sliding Door',
    category: 'doors',
    defaultWidth: 4,
    defaultHeight: 1,
    color: '#0e7490',
    icon: '🚪',
    resizable: false,
    description: 'Sliding glass door (4 ft wide)',
  },
  {
    type: 'bathroom-door',
    name: 'Bathroom Door',
    category: 'doors',
    defaultWidth: 2.5,
    defaultHeight: 1,
    color: '#0284c7',
    icon: '🚪',
    resizable: false,
    description: 'Bathroom/washroom door (2.5 ft)',
  },

  // ── Windows ───────────────────────────────────────────────────────────────
  {
    type: 'window',
    name: 'Window',
    category: 'windows',
    defaultWidth: 3,
    defaultHeight: 0.5,
    color: '#38bdf8',
    icon: '🪟',
    resizable: true,
    description: 'Standard window (3 ft wide)',
  },
  {
    type: 'large-window',
    name: 'Large Window',
    category: 'windows',
    defaultWidth: 5,
    defaultHeight: 0.5,
    color: '#0ea5e9',
    icon: '🪟',
    resizable: true,
    description: 'Large panoramic window (5 ft)',
  },
  {
    type: 'corner-window',
    name: 'Corner Window',
    category: 'windows',
    defaultWidth: 4,
    defaultHeight: 4,
    color: '#7dd3fc',
    icon: '🪟',
    resizable: true,
    description: 'Corner / bay window',
  },

  // ── Bathroom / Washroom ───────────────────────────────────────────────────
  {
    type: 'washroom',
    name: 'Washroom',
    category: 'bathroom',
    defaultWidth: 6,
    defaultHeight: 5,
    color: '#bfdbfe',
    icon: '🚿',
    resizable: true,
    description: 'Standard washroom (6×5 ft)',
  },
  {
    type: 'bathroom',
    name: 'Bathroom',
    category: 'bathroom',
    defaultWidth: 8,
    defaultHeight: 6,
    color: '#93c5fd',
    icon: '🛁',
    resizable: true,
    description: 'Full bathroom with tub (8×6 ft)',
  },
  {
    type: 'toilet',
    name: 'Toilet / WC',
    category: 'bathroom',
    defaultWidth: 5,
    defaultHeight: 4,
    color: '#a5f3fc',
    icon: '🚽',
    resizable: true,
    description: 'Toilet / WC only (5×4 ft)',
  },
  {
    type: 'bathtub',
    name: 'Bathtub',
    category: 'bathroom',
    defaultWidth: 5.5,
    defaultHeight: 2.5,
    color: '#67e8f9',
    icon: '🛁',
    resizable: false,
    description: 'Standard bathtub (5.5×2.5 ft)',
  },
  {
    type: 'shower',
    name: 'Shower Stall',
    category: 'bathroom',
    defaultWidth: 3,
    defaultHeight: 3,
    color: '#22d3ee',
    icon: '🚿',
    resizable: false,
    description: 'Shower stall (3×3 ft)',
  },
  {
    type: 'sink',
    name: 'Bathroom Sink',
    category: 'bathroom',
    defaultWidth: 2,
    defaultHeight: 1.5,
    color: '#06b6d4',
    icon: '🚰',
    resizable: false,
    description: 'Pedestal / vanity sink (2×1.5 ft)',
  },

  // ── Kitchen ───────────────────────────────────────────────────────────────
  {
    type: 'kitchen',
    name: 'Kitchen',
    category: 'kitchen',
    defaultWidth: 12,
    defaultHeight: 10,
    color: '#fde68a',
    icon: '🍳',
    resizable: true,
    description: 'Kitchen area (12×10 ft)',
  },
  {
    type: 'kitchen-counter',
    name: 'Kitchen Counter',
    category: 'kitchen',
    defaultWidth: 8,
    defaultHeight: 2,
    color: '#f59e0b',
    icon: '🧱',
    resizable: true,
    description: 'Kitchen counter top (8×2 ft)',
  },
  {
    type: 'island',
    name: 'Kitchen Island',
    category: 'kitchen',
    defaultWidth: 6,
    defaultHeight: 3,
    color: '#d97706',
    icon: '🏝️',
    resizable: true,
    description: 'Kitchen island (6×3 ft)',
  },
  {
    type: 'stove',
    name: 'Stove / Range',
    category: 'kitchen',
    defaultWidth: 2.5,
    defaultHeight: 2,
    color: '#b45309',
    icon: '🔥',
    resizable: false,
    description: 'Stove/range (2.5×2 ft)',
  },
  {
    type: 'refrigerator',
    name: 'Refrigerator',
    category: 'kitchen',
    defaultWidth: 2.5,
    defaultHeight: 2.5,
    color: '#a3a3a3',
    icon: '🧊',
    resizable: false,
    description: 'Refrigerator/fridge (2.5×2.5 ft)',
  },
  {
    type: 'dishwasher',
    name: 'Dishwasher',
    category: 'kitchen',
    defaultWidth: 2,
    defaultHeight: 2,
    color: '#d1d5db',
    icon: '🍽️',
    resizable: false,
    description: 'Built-in dishwasher (2×2 ft)',
  },

  // ── Bedroom Furniture ─────────────────────────────────────────────────────
  {
    type: 'single-bed',
    name: 'Single Bed',
    category: 'bedroom',
    defaultWidth: 3,
    defaultHeight: 6.5,
    color: '#c4b5fd',
    icon: '🛏️',
    resizable: false,
    description: 'Single bed (3×6.5 ft)',
  },
  {
    type: 'double-bed',
    name: 'Double Bed',
    category: 'bedroom',
    defaultWidth: 5,
    defaultHeight: 6.5,
    color: '#a78bfa',
    icon: '🛏️',
    resizable: false,
    description: 'Double bed (5×6.5 ft)',
  },
  {
    type: 'queen-bed',
    name: 'Queen Bed',
    category: 'bedroom',
    defaultWidth: 5.5,
    defaultHeight: 6.7,
    color: '#8b5cf6',
    icon: '🛏️',
    resizable: false,
    description: 'Queen size bed (5.5×6.7 ft)',
  },
  {
    type: 'king-bed',
    name: 'King Bed',
    category: 'bedroom',
    defaultWidth: 6.5,
    defaultHeight: 6.7,
    color: '#7c3aed',
    icon: '🛏️',
    resizable: false,
    description: 'King size bed (6.5×6.7 ft)',
  },
  {
    type: 'wardrobe',
    name: 'Wardrobe / Closet',
    category: 'bedroom',
    defaultWidth: 6,
    defaultHeight: 2,
    color: '#b45309',
    icon: '🚪',
    resizable: true,
    description: 'Built-in wardrobe (6×2 ft)',
  },
  {
    type: 'dresser',
    name: 'Dresser / Vanity',
    category: 'bedroom',
    defaultWidth: 4,
    defaultHeight: 1.5,
    color: '#d97706',
    icon: '🪞',
    resizable: false,
    description: 'Dresser with mirror (4×1.5 ft)',
  },
  {
    type: 'nightstand',
    name: 'Nightstand',
    category: 'bedroom',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#92400e',
    icon: '🪑',
    resizable: false,
    description: 'Bedside table (1.5×1.5 ft)',
  },

  // ── Living Room Furniture ─────────────────────────────────────────────────
  {
    type: 'sofa-2',
    name: '2-Seater Sofa',
    category: 'living',
    defaultWidth: 5,
    defaultHeight: 2.5,
    color: '#fca5a5',
    icon: '🛋️',
    resizable: false,
    description: '2-seater sofa (5×2.5 ft)',
  },
  {
    type: 'sofa-3',
    name: '3-Seater Sofa',
    category: 'living',
    defaultWidth: 7,
    defaultHeight: 2.5,
    color: '#f87171',
    icon: '🛋️',
    resizable: false,
    description: '3-seater sofa (7×2.5 ft)',
  },
  {
    type: 'sofa-l',
    name: 'L-Shape Sofa',
    category: 'living',
    defaultWidth: 9,
    defaultHeight: 6,
    color: '#ef4444',
    icon: '🛋️',
    resizable: false,
    description: 'L-shape sofa set (9×6 ft)',
  },
  {
    type: 'armchair',
    name: 'Armchair',
    category: 'living',
    defaultWidth: 2.5,
    defaultHeight: 2.5,
    color: '#fecaca',
    icon: '🪑',
    resizable: false,
    description: 'Single armchair (2.5×2.5 ft)',
  },
  {
    type: 'coffee-table',
    name: 'Coffee Table',
    category: 'living',
    defaultWidth: 4,
    defaultHeight: 2,
    color: '#fed7aa',
    icon: '🪵',
    resizable: false,
    description: 'Coffee/center table (4×2 ft)',
  },
  {
    type: 'tv-unit',
    name: 'TV Unit',
    category: 'living',
    defaultWidth: 6,
    defaultHeight: 1.5,
    color: '#6b7280',
    icon: '📺',
    resizable: true,
    description: 'TV stand / console (6×1.5 ft)',
  },
  {
    type: 'tv',
    name: 'Television',
    category: 'living',
    defaultWidth: 4,
    defaultHeight: 0.5,
    color: '#374151',
    icon: '📺',
    resizable: false,
    description: '55" flat screen TV (4×0.5 ft)',
  },

  // ── Dining ────────────────────────────────────────────────────────────────
  {
    type: 'dining-4',
    name: 'Dining Table (4-seat)',
    category: 'dining',
    defaultWidth: 5,
    defaultHeight: 3,
    color: '#a3e635',
    icon: '🍽️',
    resizable: false,
    description: '4-person dining table (5×3 ft)',
  },
  {
    type: 'dining-6',
    name: 'Dining Table (6-seat)',
    category: 'dining',
    defaultWidth: 7,
    defaultHeight: 3.5,
    color: '#84cc16',
    icon: '🍽️',
    resizable: false,
    description: '6-person dining table (7×3.5 ft)',
  },
  {
    type: 'dining-8',
    name: 'Dining Table (8-seat)',
    category: 'dining',
    defaultWidth: 9,
    defaultHeight: 3.5,
    color: '#65a30d',
    icon: '🍽️',
    resizable: false,
    description: '8-person dining table (9×3.5 ft)',
  },

  // ── Storage ───────────────────────────────────────────────────────────────
  {
    type: 'cabinet',
    name: 'Cabinet',
    category: 'storage',
    defaultWidth: 3,
    defaultHeight: 1.5,
    color: '#d6b895',
    icon: '🗄️',
    resizable: true,
    description: 'General storage cabinet (3×1.5 ft)',
  },
  {
    type: 'bookshelf',
    name: 'Bookshelf',
    category: 'storage',
    defaultWidth: 4,
    defaultHeight: 1,
    color: '#92400e',
    icon: '📚',
    resizable: true,
    description: 'Bookcase / bookshelf (4×1 ft)',
  },
  {
    type: 'shoe-rack',
    name: 'Shoe Rack',
    category: 'storage',
    defaultWidth: 3,
    defaultHeight: 1,
    color: '#c8a97e',
    icon: '👟',
    resizable: false,
    description: 'Shoe rack at entrance (3×1 ft)',
  },
  {
    type: 'linen-closet',
    name: 'Linen Closet',
    category: 'storage',
    defaultWidth: 3,
    defaultHeight: 1.5,
    color: '#e7d5bc',
    icon: '🗄️',
    resizable: true,
    description: 'Linen / utility closet (3×1.5 ft)',
  },

  // ── Outdoor / Exterior ────────────────────────────────────────────────────
  {
    type: 'main-gate',
    name: 'Main Gate',
    category: 'outdoor',
    defaultWidth: 10,
    defaultHeight: 1.5,
    color: '#1e3a5f',
    icon: '🏗️',
    resizable: true,
    description: 'Main vehicle/pedestrian gate (10×1.5 ft)',
  },
  {
    type: 'garage',
    name: 'Garage',
    category: 'outdoor',
    defaultWidth: 20,
    defaultHeight: 12,
    color: '#94a3b8',
    icon: '🚗',
    resizable: true,
    description: 'Car garage (20×12 ft)',
  },
  {
    type: 'car-parking',
    name: 'Car Parking',
    category: 'outdoor',
    defaultWidth: 9,
    defaultHeight: 18,
    color: '#cbd5e1',
    icon: '🅿️',
    resizable: true,
    description: 'Open car parking space (9×18 ft)',
  },
  {
    type: 'balcony',
    name: 'Balcony',
    category: 'outdoor',
    defaultWidth: 10,
    defaultHeight: 5,
    color: '#bbf7d0',
    icon: '🌿',
    resizable: true,
    description: 'Outdoor balcony (10×5 ft)',
  },
  {
    type: 'garden',
    name: 'Garden / Lawn',
    category: 'outdoor',
    defaultWidth: 15,
    defaultHeight: 10,
    color: '#86efac',
    icon: '🌳',
    resizable: true,
    description: 'Garden or lawn area',
  },
  {
    type: 'patio',
    name: 'Patio / Terrace',
    category: 'outdoor',
    defaultWidth: 12,
    defaultHeight: 8,
    color: '#a7f3d0',
    icon: '🪴',
    resizable: true,
    description: 'Outdoor patio or terrace',
  },
  {
    type: 'boundary-wall',
    name: 'Boundary Wall',
    category: 'outdoor',
    defaultWidth: 20,
    defaultHeight: 1,
    color: '#475569',
    icon: '🧱',
    resizable: true,
    description: 'Exterior boundary / perimeter wall',
  },

  // ── Stairs ────────────────────────────────────────────────────────────────
  {
    type: 'stairs',
    name: 'Staircase',
    category: 'stairs',
    defaultWidth: 4,
    defaultHeight: 10,
    color: '#fbbf24',
    icon: '🪜',
    resizable: true,
    description: 'Straight staircase (4×10 ft)',
  },
  {
    type: 'spiral-stairs',
    name: 'Spiral Stairs',
    category: 'stairs',
    defaultWidth: 5,
    defaultHeight: 5,
    color: '#f59e0b',
    icon: '🌀',
    resizable: false,
    description: 'Spiral staircase (5×5 ft)',
  },
  {
    type: 'landing',
    name: 'Landing / Corridor',
    category: 'stairs',
    defaultWidth: 8,
    defaultHeight: 4,
    color: '#e2e8f0',
    icon: '➡️',
    resizable: true,
    description: 'Hallway, corridor, or landing',
  },

  // ── Study / Office ────────────────────────────────────────────────────────
  {
    type: 'study-desk',
    name: 'Study Desk',
    category: 'study',
    defaultWidth: 4,
    defaultHeight: 2,
    color: '#bfdbfe',
    icon: '🖥️',
    resizable: false,
    description: 'Study/computer desk (4×2 ft)',
  },
  {
    type: 'office-chair',
    name: 'Office Chair',
    category: 'study',
    defaultWidth: 2,
    defaultHeight: 2,
    color: '#93c5fd',
    icon: '🪑',
    resizable: false,
    description: 'Desk/office chair (2×2 ft)',
  },
];

export const ITEM_CATEGORIES: Record<string, string> = {
  structure: 'Structure & Walls',
  rooms: 'Rooms',
  doors: 'Doors',
  windows: 'Windows',
  bathroom: 'Bathroom / Washroom',
  kitchen: 'Kitchen',
  bedroom: 'Bedroom Furniture',
  living: 'Living Room',
  dining: 'Dining',
  storage: 'Storage',
  outdoor: 'Outdoor / Exterior',
  stairs: 'Stairs & Corridors',
  study: 'Study & Office',
};

export function getItemByType(type: string): ItemDefinition | undefined {
  return ITEM_LIBRARY.find((i) => i.type === type);
}
