import { ItemDefinition, ItemCategory } from '@/types';
import type { DrawingType } from '@/lib/drawingTypes';

export const ITEM_LIBRARY: ItemDefinition[] = [
  // ── Structure ─────────────────────────────────────────────────────────────
  {
    type: 'plot-boundary',
    name: 'Plot Boundary',
    category: 'structure',
    defaultWidth: 40,
    defaultHeight: 30,
    color: '#1e293b',
    icon: '⬛',
    resizable: true,
    description: 'Outer plot boundary',
  },
  {
    type: 'wall-h',
    name: 'Wall (Horizontal)',
    category: 'structure',
    defaultWidth: 12,
    defaultHeight: 0.75,
    color: '#374151',
    icon: '▬',
    resizable: true,
    description: 'Horizontal interior or exterior wall',
  },
  {
    type: 'wall-v',
    name: 'Wall (Vertical)',
    category: 'structure',
    defaultWidth: 0.75,
    defaultHeight: 12,
    color: '#374151',
    icon: '▮',
    resizable: true,
    description: 'Vertical interior or exterior wall',
  },
  {
    type: 'wall',
    name: 'Wall (Custom)',
    category: 'structure',
    defaultWidth: 10,
    defaultHeight: 0.75,
    color: '#374151',
    icon: '▬',
    resizable: true,
    description: 'Custom-size wall — rotate freely',
  },
  {
    type: 'exterior-wall-h',
    name: 'Exterior Wall (H)',
    category: 'structure',
    defaultWidth: 20,
    defaultHeight: 1,
    color: '#1e293b',
    icon: '▬',
    resizable: true,
    description: 'Thick horizontal exterior/boundary wall (1 ft)',
  },
  {
    type: 'exterior-wall-v',
    name: 'Exterior Wall (V)',
    category: 'structure',
    defaultWidth: 1,
    defaultHeight: 20,
    color: '#1e293b',
    icon: '▮',
    resizable: true,
    description: 'Thick vertical exterior/boundary wall (1 ft)',
  },
  {
    type: 'column',
    name: 'Column / Pillar',
    category: 'structure',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#6b7280',
    icon: '⬜',
    resizable: false,
    description: 'Structural column or pillar',
  },

  // ── Rooms ─────────────────────────────────────────────────────────────────
  {
    type: 'room',
    name: 'Room',
    category: 'rooms',
    defaultWidth: 12,
    defaultHeight: 10,
    color: '#dbeafe',
    icon: '🏠',
    resizable: true,
    description: 'Generic room (12×10 ft)',
  },
  {
    type: 'master-bedroom',
    name: 'Master Bedroom',
    category: 'rooms',
    defaultWidth: 14,
    defaultHeight: 12,
    color: '#ede9fe',
    icon: '🛏️',
    resizable: true,
    description: 'Master bedroom (14×12 ft)',
  },
  {
    type: 'bedroom',
    name: 'Bedroom',
    category: 'rooms',
    defaultWidth: 12,
    defaultHeight: 10,
    color: '#fce7f3',
    icon: '🛏️',
    resizable: true,
    description: 'Standard bedroom (12×10 ft)',
  },
  {
    type: 'kids-room',
    name: "Kids' Room",
    category: 'rooms',
    defaultWidth: 10,
    defaultHeight: 10,
    color: '#dcfce7',
    icon: '🧸',
    resizable: true,
    description: "Children's room (10×10 ft)",
  },
  {
    type: 'guest-room',
    name: 'Guest Room',
    category: 'rooms',
    defaultWidth: 11,
    defaultHeight: 10,
    color: '#fff7ed',
    icon: '🛏️',
    resizable: true,
    description: 'Guest bedroom (11×10 ft)',
  },
  {
    type: 'living-room',
    name: 'Living Room',
    category: 'rooms',
    defaultWidth: 18,
    defaultHeight: 14,
    color: '#fef9c3',
    icon: '🛋️',
    resizable: true,
    description: 'Living/drawing room (18×14 ft)',
  },
  {
    type: 'drawing-room',
    name: 'Drawing Room',
    category: 'rooms',
    defaultWidth: 16,
    defaultHeight: 12,
    color: '#fef3c7',
    icon: '🖼️',
    resizable: true,
    description: 'Formal drawing room (16×12 ft)',
  },
  {
    type: 'study',
    name: 'Study / Office',
    category: 'rooms',
    defaultWidth: 10,
    defaultHeight: 10,
    color: '#e0f2fe',
    icon: '📚',
    resizable: true,
    description: 'Home study or office (10×10 ft)',
  },
  {
    type: 'prayer-room',
    name: 'Prayer Room',
    category: 'rooms',
    defaultWidth: 8,
    defaultHeight: 8,
    color: '#f0fdf4',
    icon: '🕌',
    resizable: true,
    description: 'Prayer / Namaz room (8×8 ft)',
  },
  {
    type: 'store-room',
    name: 'Store Room',
    category: 'rooms',
    defaultWidth: 8,
    defaultHeight: 6,
    color: '#fdf4ff',
    icon: '📦',
    resizable: true,
    description: 'Storage / utility room (8×6 ft)',
  },

  // ── Doors ─────────────────────────────────────────────────────────────────
  {
    type: 'main-door',
    name: 'Main Entrance Door',
    category: 'doors',
    defaultWidth: 4,
    defaultHeight: 1,
    color: '#92400e',
    icon: '🚪',
    resizable: false,
    description: 'Main front door (4 ft wide)',
  },
  {
    type: 'single-door',
    name: 'Single Door',
    category: 'doors',
    defaultWidth: 3,
    defaultHeight: 1,
    color: '#b45309',
    icon: '🚪',
    resizable: false,
    description: 'Standard single door (3 ft wide)',
  },
  {
    type: 'double-door',
    name: 'Double Door',
    category: 'doors',
    defaultWidth: 5,
    defaultHeight: 1,
    color: '#a16207',
    icon: '🚪',
    resizable: false,
    description: 'Double swing door (5 ft wide)',
  },
  {
    type: 'sliding-door',
    name: 'Sliding Door',
    category: 'doors',
    defaultWidth: 4,
    defaultHeight: 1,
    color: '#0e7490',
    icon: '🚪',
    resizable: false,
    description: 'Sliding glass door (4 ft wide)',
  },
  {
    type: 'bathroom-door',
    name: 'Bathroom Door',
    category: 'doors',
    defaultWidth: 2.5,
    defaultHeight: 1,
    color: '#0284c7',
    icon: '🚪',
    resizable: false,
    description: 'Bathroom/washroom door (2.5 ft)',
  },

  // ── Windows ───────────────────────────────────────────────────────────────
  {
    type: 'window',
    name: 'Window',
    category: 'windows',
    defaultWidth: 3,
    defaultHeight: 0.5,
    color: '#38bdf8',
    icon: '🪟',
    resizable: true,
    description: 'Standard window (3 ft wide)',
  },
  {
    type: 'large-window',
    name: 'Large Window',
    category: 'windows',
    defaultWidth: 5,
    defaultHeight: 0.5,
    color: '#0ea5e9',
    icon: '🪟',
    resizable: true,
    description: 'Large panoramic window (5 ft)',
  },
  {
    type: 'corner-window',
    name: 'Corner Window',
    category: 'windows',
    defaultWidth: 4,
    defaultHeight: 4,
    color: '#7dd3fc',
    icon: '🪟',
    resizable: true,
    description: 'Corner / bay window',
  },

  // ── Bathroom / Washroom ───────────────────────────────────────────────────
  {
    type: 'washroom',
    name: 'Washroom',
    category: 'bathroom',
    defaultWidth: 6,
    defaultHeight: 5,
    color: '#bfdbfe',
    icon: '🚿',
    resizable: true,
    description: 'Standard washroom (6×5 ft)',
  },
  {
    type: 'bathroom',
    name: 'Bathroom',
    category: 'bathroom',
    defaultWidth: 8,
    defaultHeight: 6,
    color: '#93c5fd',
    icon: '🛁',
    resizable: true,
    description: 'Full bathroom with tub (8×6 ft)',
  },
  {
    type: 'toilet',
    name: 'Toilet / WC',
    category: 'bathroom',
    defaultWidth: 5,
    defaultHeight: 4,
    color: '#a5f3fc',
    icon: '🚽',
    resizable: true,
    description: 'Toilet / WC only (5×4 ft)',
  },
  {
    type: 'bathtub',
    name: 'Bathtub',
    category: 'bathroom',
    defaultWidth: 5.5,
    defaultHeight: 2.5,
    color: '#67e8f9',
    icon: '🛁',
    resizable: false,
    description: 'Standard bathtub (5.5×2.5 ft)',
  },
  {
    type: 'shower',
    name: 'Shower Stall',
    category: 'bathroom',
    defaultWidth: 3,
    defaultHeight: 3,
    color: '#22d3ee',
    icon: '🚿',
    resizable: false,
    description: 'Shower stall (3×3 ft)',
  },
  {
    type: 'sink',
    name: 'Bathroom Sink',
    category: 'bathroom',
    defaultWidth: 2,
    defaultHeight: 1.5,
    color: '#06b6d4',
    icon: '🚰',
    resizable: false,
    description: 'Pedestal / vanity sink (2×1.5 ft)',
  },

  // ── Kitchen ───────────────────────────────────────────────────────────────
  {
    type: 'kitchen',
    name: 'Kitchen',
    category: 'kitchen',
    defaultWidth: 12,
    defaultHeight: 10,
    color: '#fde68a',
    icon: '🍳',
    resizable: true,
    description: 'Kitchen area (12×10 ft)',
  },
  {
    type: 'kitchen-counter',
    name: 'Kitchen Counter',
    category: 'kitchen',
    defaultWidth: 8,
    defaultHeight: 2,
    color: '#f59e0b',
    icon: '🧱',
    resizable: true,
    description: 'Kitchen counter top (8×2 ft)',
  },
  {
    type: 'island',
    name: 'Kitchen Island',
    category: 'kitchen',
    defaultWidth: 6,
    defaultHeight: 3,
    color: '#d97706',
    icon: '🏝️',
    resizable: true,
    description: 'Kitchen island (6×3 ft)',
  },
  {
    type: 'stove',
    name: 'Stove / Range',
    category: 'kitchen',
    defaultWidth: 2.5,
    defaultHeight: 2,
    color: '#b45309',
    icon: '🔥',
    resizable: false,
    description: 'Stove/range (2.5×2 ft)',
  },
  {
    type: 'refrigerator',
    name: 'Refrigerator',
    category: 'kitchen',
    defaultWidth: 2.5,
    defaultHeight: 2.5,
    color: '#a3a3a3',
    icon: '🧊',
    resizable: false,
    description: 'Refrigerator/fridge (2.5×2.5 ft)',
  },
  {
    type: 'dishwasher',
    name: 'Dishwasher',
    category: 'kitchen',
    defaultWidth: 2,
    defaultHeight: 2,
    color: '#d1d5db',
    icon: '🍽️',
    resizable: false,
    description: 'Built-in dishwasher (2×2 ft)',
  },

  // ── Bedroom Furniture ─────────────────────────────────────────────────────
  {
    type: 'single-bed',
    name: 'Single Bed',
    category: 'bedroom',
    defaultWidth: 3,
    defaultHeight: 6.5,
    color: '#c4b5fd',
    icon: '🛏️',
    resizable: false,
    description: 'Single bed (3×6.5 ft)',
  },
  {
    type: 'double-bed',
    name: 'Double Bed',
    category: 'bedroom',
    defaultWidth: 5,
    defaultHeight: 6.5,
    color: '#a78bfa',
    icon: '🛏️',
    resizable: false,
    description: 'Double bed (5×6.5 ft)',
  },
  {
    type: 'queen-bed',
    name: 'Queen Bed',
    category: 'bedroom',
    defaultWidth: 5.5,
    defaultHeight: 6.7,
    color: '#8b5cf6',
    icon: '🛏️',
    resizable: false,
    description: 'Queen size bed (5.5×6.7 ft)',
  },
  {
    type: 'king-bed',
    name: 'King Bed',
    category: 'bedroom',
    defaultWidth: 6.5,
    defaultHeight: 6.7,
    color: '#7c3aed',
    icon: '🛏️',
    resizable: false,
    description: 'King size bed (6.5×6.7 ft)',
  },
  {
    type: 'wardrobe',
    name: 'Wardrobe / Closet',
    category: 'bedroom',
    defaultWidth: 6,
    defaultHeight: 2,
    color: '#b45309',
    icon: '🚪',
    resizable: true,
    description: 'Built-in wardrobe (6×2 ft)',
  },
  {
    type: 'dresser',
    name: 'Dresser / Vanity',
    category: 'bedroom',
    defaultWidth: 4,
    defaultHeight: 1.5,
    color: '#d97706',
    icon: '🪞',
    resizable: false,
    description: 'Dresser with mirror (4×1.5 ft)',
  },
  {
    type: 'nightstand',
    name: 'Nightstand',
    category: 'bedroom',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#92400e',
    icon: '🪑',
    resizable: false,
    description: 'Bedside table (1.5×1.5 ft)',
  },

  // ── Living Room Furniture ─────────────────────────────────────────────────
  {
    type: 'sofa-2',
    name: '2-Seater Sofa',
    category: 'living',
    defaultWidth: 5,
    defaultHeight: 2.5,
    color: '#fca5a5',
    icon: '🛋️',
    resizable: false,
    description: '2-seater sofa (5×2.5 ft)',
  },
  {
    type: 'sofa-3',
    name: '3-Seater Sofa',
    category: 'living',
    defaultWidth: 7,
    defaultHeight: 2.5,
    color: '#f87171',
    icon: '🛋️',
    resizable: false,
    description: '3-seater sofa (7×2.5 ft)',
  },
  {
    type: 'sofa-l',
    name: 'L-Shape Sofa',
    category: 'living',
    defaultWidth: 9,
    defaultHeight: 6,
    color: '#ef4444',
    icon: '🛋️',
    resizable: false,
    description: 'L-shape sofa set (9×6 ft)',
  },
  {
    type: 'armchair',
    name: 'Armchair',
    category: 'living',
    defaultWidth: 2.5,
    defaultHeight: 2.5,
    color: '#fecaca',
    icon: '🪑',
    resizable: false,
    description: 'Single armchair (2.5×2.5 ft)',
  },
  {
    type: 'coffee-table',
    name: 'Coffee Table',
    category: 'living',
    defaultWidth: 4,
    defaultHeight: 2,
    color: '#fed7aa',
    icon: '🪵',
    resizable: false,
    description: 'Coffee/center table (4×2 ft)',
  },
  {
    type: 'tv-unit',
    name: 'TV Unit',
    category: 'living',
    defaultWidth: 6,
    defaultHeight: 1.5,
    color: '#6b7280',
    icon: '📺',
    resizable: true,
    description: 'TV stand / console (6×1.5 ft)',
  },
  {
    type: 'tv',
    name: 'Television',
    category: 'living',
    defaultWidth: 4,
    defaultHeight: 0.5,
    color: '#374151',
    icon: '📺',
    resizable: false,
    description: '55" flat screen TV (4×0.5 ft)',
  },

  // ── Dining ────────────────────────────────────────────────────────────────
  {
    type: 'dining-4',
    name: 'Dining Table (4-seat)',
    category: 'dining',
    defaultWidth: 5,
    defaultHeight: 3,
    color: '#a3e635',
    icon: '🍽️',
    resizable: false,
    description: '4-person dining table (5×3 ft)',
  },
  {
    type: 'dining-6',
    name: 'Dining Table (6-seat)',
    category: 'dining',
    defaultWidth: 7,
    defaultHeight: 3.5,
    color: '#84cc16',
    icon: '🍽️',
    resizable: false,
    description: '6-person dining table (7×3.5 ft)',
  },
  {
    type: 'dining-8',
    name: 'Dining Table (8-seat)',
    category: 'dining',
    defaultWidth: 9,
    defaultHeight: 3.5,
    color: '#65a30d',
    icon: '🍽️',
    resizable: false,
    description: '8-person dining table (9×3.5 ft)',
  },

  // ── Storage ───────────────────────────────────────────────────────────────
  {
    type: 'cabinet',
    name: 'Cabinet',
    category: 'storage',
    defaultWidth: 3,
    defaultHeight: 1.5,
    color: '#d6b895',
    icon: '🗄️',
    resizable: true,
    description: 'General storage cabinet (3×1.5 ft)',
  },
  {
    type: 'bookshelf',
    name: 'Bookshelf',
    category: 'storage',
    defaultWidth: 4,
    defaultHeight: 1,
    color: '#92400e',
    icon: '📚',
    resizable: true,
    description: 'Bookcase / bookshelf (4×1 ft)',
  },
  {
    type: 'shoe-rack',
    name: 'Shoe Rack',
    category: 'storage',
    defaultWidth: 3,
    defaultHeight: 1,
    color: '#c8a97e',
    icon: '👟',
    resizable: false,
    description: 'Shoe rack at entrance (3×1 ft)',
  },
  {
    type: 'linen-closet',
    name: 'Linen Closet',
    category: 'storage',
    defaultWidth: 3,
    defaultHeight: 1.5,
    color: '#e7d5bc',
    icon: '🗄️',
    resizable: true,
    description: 'Linen / utility closet (3×1.5 ft)',
  },

  // ── Outdoor / Exterior ────────────────────────────────────────────────────
  {
    type: 'main-gate',
    name: 'Main Gate',
    category: 'outdoor',
    defaultWidth: 10,
    defaultHeight: 1.5,
    color: '#1e3a5f',
    icon: '🏗️',
    resizable: true,
    description: 'Main vehicle/pedestrian gate (10×1.5 ft)',
  },
  {
    type: 'garage',
    name: 'Garage',
    category: 'outdoor',
    defaultWidth: 20,
    defaultHeight: 12,
    color: '#94a3b8',
    icon: '🚗',
    resizable: true,
    description: 'Car garage (20×12 ft)',
  },
  {
    type: 'car-parking',
    name: 'Car Parking',
    category: 'outdoor',
    defaultWidth: 9,
    defaultHeight: 18,
    color: '#cbd5e1',
    icon: '🅿️',
    resizable: true,
    description: 'Open car parking space (9×18 ft)',
  },
  {
    type: 'balcony',
    name: 'Balcony',
    category: 'outdoor',
    defaultWidth: 10,
    defaultHeight: 5,
    color: '#bbf7d0',
    icon: '🌿',
    resizable: true,
    description: 'Outdoor balcony (10×5 ft)',
  },
  {
    type: 'garden',
    name: 'Garden / Lawn',
    category: 'outdoor',
    defaultWidth: 15,
    defaultHeight: 10,
    color: '#86efac',
    icon: '🌳',
    resizable: true,
    description: 'Garden or lawn area',
  },
  {
    type: 'patio',
    name: 'Patio / Terrace',
    category: 'outdoor',
    defaultWidth: 12,
    defaultHeight: 8,
    color: '#a7f3d0',
    icon: '🪴',
    resizable: true,
    description: 'Outdoor patio or terrace',
  },
  {
    type: 'boundary-wall',
    name: 'Boundary Wall',
    category: 'outdoor',
    defaultWidth: 20,
    defaultHeight: 1,
    color: '#475569',
    icon: '🧱',
    resizable: true,
    description: 'Exterior boundary / perimeter wall',
  },

  // ── Stairs ────────────────────────────────────────────────────────────────
  {
    type: 'stairs',
    name: 'Staircase',
    category: 'stairs',
    defaultWidth: 4,
    defaultHeight: 10,
    color: '#fbbf24',
    icon: '🪜',
    resizable: true,
    description: 'Straight staircase (4×10 ft)',
  },
  {
    type: 'spiral-stairs',
    name: 'Spiral Stairs',
    category: 'stairs',
    defaultWidth: 5,
    defaultHeight: 5,
    color: '#f59e0b',
    icon: '🌀',
    resizable: false,
    description: 'Spiral staircase (5×5 ft)',
  },
  {
    type: 'landing',
    name: 'Landing / Corridor',
    category: 'stairs',
    defaultWidth: 8,
    defaultHeight: 4,
    color: '#e2e8f0',
    icon: '➡️',
    resizable: true,
    description: 'Hallway, corridor, or landing',
  },

  // ── Study / Office ────────────────────────────────────────────────────────
  {
    type: 'study-desk',
    name: 'Study Desk',
    category: 'study',
    defaultWidth: 4,
    defaultHeight: 2,
    color: '#bfdbfe',
    icon: '🖥️',
    resizable: false,
    description: 'Study/computer desk (4×2 ft)',
  },
  {
    type: 'office-chair',
    name: 'Office Chair',
    category: 'study',
    defaultWidth: 2,
    defaultHeight: 2,
    color: '#93c5fd',
    icon: '🪑',
    resizable: false,
    description: 'Desk/office chair (2×2 ft)',
  },

  // ── Pathways & Roads ──────────────────────────────────────────────────────
  {
    type: 'pathway',
    name: 'Walkway / Path',
    category: 'pathway',
    defaultWidth: 3,
    defaultHeight: 10,
    color: '#d4d4d4',
    icon: '🚶',
    resizable: true,
    description: 'Pedestrian walkway or garden path (3×10 ft)',
  },
  {
    type: 'road',
    name: 'Road',
    category: 'pathway',
    defaultWidth: 12,
    defaultHeight: 30,
    color: '#6b7280',
    icon: '🛣️',
    resizable: true,
    description: 'Road or street segment (12×30 ft)',
  },
  {
    type: 'driveway',
    name: 'Driveway',
    category: 'pathway',
    defaultWidth: 10,
    defaultHeight: 20,
    color: '#9ca3af',
    icon: '🚗',
    resizable: true,
    description: 'Car driveway (10×20 ft)',
  },
  {
    type: 'footpath',
    name: 'Footpath / Sidewalk',
    category: 'pathway',
    defaultWidth: 4,
    defaultHeight: 20,
    color: '#e5e7eb',
    icon: '🚶',
    resizable: true,
    description: 'Paved footpath or sidewalk (4×20 ft)',
  },
  {
    type: 'lane',
    name: 'Lane / Alley',
    category: 'pathway',
    defaultWidth: 6,
    defaultHeight: 20,
    color: '#b5bec9',
    icon: '↔️',
    resizable: true,
    description: 'Narrow lane or back alley (6×20 ft)',
  },
  {
    type: 'garden-path',
    name: 'Garden Path',
    category: 'pathway',
    defaultWidth: 2,
    defaultHeight: 8,
    color: '#a3e635',
    icon: '🌿',
    resizable: true,
    description: 'Decorative garden stepping-stone path (2×8 ft)',
  },
  {
    type: 'bridge',
    name: 'Bridge / Ramp',
    category: 'pathway',
    defaultWidth: 6,
    defaultHeight: 12,
    color: '#94a3b8',
    icon: '🌉',
    resizable: true,
    description: 'Pedestrian bridge or access ramp (6×12 ft)',
  },

  // ── Electrical ───────────────────────────────────────────────────────────
  {
    type: 'ceiling-light',
    name: 'Ceiling Light',
    category: 'electrical',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#fbbf24',
    icon: '💡',
    resizable: true,
    description: 'Ceiling light / batten fixture (1.5×1.5 ft)',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'ceiling-fan',
    name: 'Ceiling Fan',
    category: 'electrical',
    defaultWidth: 4,
    defaultHeight: 4,
    color: '#f59e0b',
    icon: '🌀',
    resizable: true,
    description: 'Ceiling fan (4×4 ft sweep)',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'switch-single',
    name: 'Switch (Single)',
    category: 'electrical',
    defaultWidth: 0.5,
    defaultHeight: 0.5,
    color: '#d97706',
    icon: '🔲',
    resizable: false,
    description: 'Single electrical switch on wall',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'switch-double',
    name: 'Switch (Double)',
    category: 'electrical',
    defaultWidth: 0.75,
    defaultHeight: 0.5,
    color: '#d97706',
    icon: '⬛',
    resizable: false,
    description: 'Double gang switch on wall',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'socket',
    name: 'Power Socket',
    category: 'electrical',
    defaultWidth: 0.5,
    defaultHeight: 0.5,
    color: '#b45309',
    icon: '🔌',
    resizable: false,
    description: 'AC power socket / outlet',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'ac-unit',
    name: 'AC Unit',
    category: 'electrical',
    defaultWidth: 3,
    defaultHeight: 1,
    color: '#0ea5e9',
    icon: '❄️',
    resizable: true,
    description: 'Split/window AC unit (3×1 ft wall-mount)',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'db-board',
    name: 'Distribution Board',
    category: 'electrical',
    defaultWidth: 1.5,
    defaultHeight: 2,
    color: '#78350f',
    icon: '⚡',
    resizable: true,
    description: 'Main distribution board / fuse box',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'exhaust-fan',
    name: 'Exhaust Fan',
    category: 'electrical',
    defaultWidth: 1,
    defaultHeight: 1,
    color: '#92400e',
    icon: '💨',
    resizable: false,
    description: 'Exhaust fan (1×1 ft wall/ceiling)',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'wiring-h',
    name: 'Wiring (Horizontal)',
    category: 'electrical',
    defaultWidth: 8,
    defaultHeight: 0.25,
    color: '#f59e0b',
    icon: '〰️',
    resizable: true,
    description: 'Electrical conduit / wiring run (horizontal)',
    drawingType: 'electrical' as DrawingType,
  },
  {
    type: 'wiring-v',
    name: 'Wiring (Vertical)',
    category: 'electrical',
    defaultWidth: 0.25,
    defaultHeight: 8,
    color: '#f59e0b',
    icon: '〰️',
    resizable: true,
    description: 'Electrical conduit / wiring run (vertical)',
    drawingType: 'electrical' as DrawingType,
  },

  // ── Plumbing ─────────────────────────────────────────────────────────────
  {
    type: 'overhead-tank',
    name: 'Overhead Tank',
    category: 'plumbing',
    defaultWidth: 4,
    defaultHeight: 3,
    color: '#0891b2',
    icon: '🪣',
    resizable: true,
    description: 'Overhead water storage tank (4×3 ft)',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'underground-tank',
    name: 'Underground Tank',
    category: 'plumbing',
    defaultWidth: 6,
    defaultHeight: 4,
    color: '#0e7490',
    icon: '💧',
    resizable: true,
    description: 'Underground water storage tank (6×4 ft)',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'water-pump',
    name: 'Water Pump',
    category: 'plumbing',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#06b6d4',
    icon: '⚙️',
    resizable: true,
    description: 'Submersible / surface water pump',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'geyser',
    name: 'Geyser / Water Heater',
    category: 'plumbing',
    defaultWidth: 1.5,
    defaultHeight: 1.5,
    color: '#f97316',
    icon: '🔥',
    resizable: true,
    description: 'Electric or gas water heater',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'supply-pipe-h',
    name: 'Supply Pipe (H)',
    category: 'plumbing',
    defaultWidth: 8,
    defaultHeight: 0.3,
    color: '#0284c7',
    icon: '—',
    resizable: true,
    description: 'Horizontal water supply pipe',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'supply-pipe-v',
    name: 'Supply Pipe (V)',
    category: 'plumbing',
    defaultWidth: 0.3,
    defaultHeight: 8,
    color: '#0284c7',
    icon: '|',
    resizable: true,
    description: 'Vertical water supply pipe',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'drain-pipe-h',
    name: 'Drain Pipe (H)',
    category: 'plumbing',
    defaultWidth: 8,
    defaultHeight: 0.3,
    color: '#854d0e',
    icon: '—',
    resizable: true,
    description: 'Horizontal drainage pipe',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'drain-pipe-v',
    name: 'Drain Pipe (V)',
    category: 'plumbing',
    defaultWidth: 0.3,
    defaultHeight: 8,
    color: '#854d0e',
    icon: '|',
    resizable: true,
    description: 'Vertical drainage pipe',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'stopcock',
    name: 'Stopcock / Valve',
    category: 'plumbing',
    defaultWidth: 0.5,
    defaultHeight: 0.5,
    color: '#155e75',
    icon: '🔩',
    resizable: false,
    description: 'Water shutoff valve or stopcock',
    drawingType: 'plumbing' as DrawingType,
  },
  {
    type: 'floor-drain',
    name: 'Floor Drain',
    category: 'plumbing',
    defaultWidth: 0.5,
    defaultHeight: 0.5,
    color: '#6b7280',
    icon: '⊘',
    resizable: false,
    description: 'Floor drain / trap point',
    drawingType: 'plumbing' as DrawingType,
  },

  // ── Structural Engineering ────────────────────────────────────────────────
  {
    type: 'rcc-column',
    name: 'RCC Column',
    category: 'structural-eng',
    defaultWidth: 1,
    defaultHeight: 1,
    color: '#292524',
    icon: '⬛',
    resizable: true,
    description: 'Reinforced concrete column (1×1 ft)',
    drawingType: 'structural' as DrawingType,
  },
  {
    type: 'beam-h',
    name: 'Beam (Horizontal)',
    category: 'structural-eng',
    defaultWidth: 12,
    defaultHeight: 1,
    color: '#44403c',
    icon: '━',
    resizable: true,
    description: 'Horizontal RCC beam (12×1 ft)',
    drawingType: 'structural' as DrawingType,
  },
  {
    type: 'beam-v',
    name: 'Beam (Vertical)',
    category: 'structural-eng',
    defaultWidth: 1,
    defaultHeight: 12,
    color: '#44403c',
    icon: '┃',
    resizable: true,
    description: 'Vertical RCC beam (1×12 ft)',
    drawingType: 'structural' as DrawingType,
  },
  {
    type: 'rcc-slab',
    name: 'RCC Slab',
    category: 'structural-eng',
    defaultWidth: 12,
    defaultHeight: 12,
    color: '#78716c',
    icon: '▪️',
    resizable: true,
    description: 'Reinforced concrete roof/floor slab',
    drawingType: 'structural' as DrawingType,
  },
  {
    type: 'lb-wall-h',
    name: 'Load-Bearing Wall (H)',
    category: 'structural-eng',
    defaultWidth: 12,
    defaultHeight: 0.75,
    color: '#292524',
    icon: '━',
    resizable: true,
    description: 'Horizontal load-bearing wall',
    drawingType: 'structural' as DrawingType,
  },
  {
    type: 'lb-wall-v',
    name: 'Load-Bearing Wall (V)',
    category: 'structural-eng',
    defaultWidth: 0.75,
    defaultHeight: 12,
    color: '#292524',
    icon: '┃',
    resizable: true,
    description: 'Vertical load-bearing wall',
    drawingType: 'structural' as DrawingType,
  },
  {
    type: 'steel-lintel',
    name: 'Steel Lintel',
    category: 'structural-eng',
    defaultWidth: 4,
    defaultHeight: 0.5,
    color: '#1c1917',
    icon: '━',
    resizable: true,
    description: 'Steel lintel over door/window opening',
    drawingType: 'structural' as DrawingType,
  },

  // ── Foundation Engineering ────────────────────────────────────────────────
  {
    type: 'col-footing',
    name: 'Column Footing',
    category: 'foundation-eng',
    defaultWidth: 3,
    defaultHeight: 3,
    color: '#57534e',
    icon: '⬜',
    resizable: true,
    description: 'Isolated column footing (3×3 ft)',
    drawingType: 'foundation' as DrawingType,
  },
  {
    type: 'strip-footing-h',
    name: 'Strip Footing (H)',
    category: 'foundation-eng',
    defaultWidth: 12,
    defaultHeight: 2,
    color: '#79716b',
    icon: '━',
    resizable: true,
    description: 'Horizontal strip footing under wall',
    drawingType: 'foundation' as DrawingType,
  },
  {
    type: 'strip-footing-v',
    name: 'Strip Footing (V)',
    category: 'foundation-eng',
    defaultWidth: 2,
    defaultHeight: 12,
    color: '#79716b',
    icon: '┃',
    resizable: true,
    description: 'Vertical strip footing under wall',
    drawingType: 'foundation' as DrawingType,
  },
  {
    type: 'plinth-beam',
    name: 'Plinth Beam',
    category: 'foundation-eng',
    defaultWidth: 12,
    defaultHeight: 1,
    color: '#44403c',
    icon: '━',
    resizable: true,
    description: 'Plinth beam at ground level',
    drawingType: 'foundation' as DrawingType,
  },
  {
    type: 'dpc-layer',
    name: 'DPC Layer',
    category: 'foundation-eng',
    defaultWidth: 12,
    defaultHeight: 0.25,
    color: '#a8a29e',
    icon: '━',
    resizable: true,
    description: 'Damp proof course layer',
    drawingType: 'foundation' as DrawingType,
  },
  {
    type: 'pad-footing',
    name: 'Pad Footing',
    category: 'foundation-eng',
    defaultWidth: 4,
    defaultHeight: 4,
    color: '#57534e',
    icon: '⬜',
    resizable: true,
    description: 'Pad/raft footing (4×4 ft)',
    drawingType: 'foundation' as DrawingType,
  },

  // ── Site Plan ─────────────────────────────────────────────────────────────
  {
    type: 'tree',
    name: 'Tree',
    category: 'site',
    defaultWidth: 4,
    defaultHeight: 4,
    color: '#15803d',
    icon: '🌳',
    resizable: true,
    description: 'Large tree (4×4 ft canopy)',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'shrub',
    name: 'Shrub / Bush',
    category: 'site',
    defaultWidth: 2,
    defaultHeight: 2,
    color: '#16a34a',
    icon: '🌿',
    resizable: true,
    description: 'Shrub or ornamental bush',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'parking-spot',
    name: 'Parking Spot',
    category: 'site',
    defaultWidth: 9,
    defaultHeight: 18,
    color: '#4b5563',
    icon: '🅿️',
    resizable: true,
    description: 'Single parking stall (9×18 ft standard)',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'setback-line',
    name: 'Setback Line',
    category: 'site',
    defaultWidth: 40,
    defaultHeight: 0.5,
    color: '#dc2626',
    icon: '⛔',
    resizable: true,
    description: 'Required building setback line (dashed)',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'landscape-area',
    name: 'Landscape Area',
    category: 'site',
    defaultWidth: 10,
    defaultHeight: 8,
    color: '#22c55e',
    icon: '🌱',
    resizable: true,
    description: 'Landscaped / green area',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'building-footprint',
    name: 'Building Footprint',
    category: 'site',
    defaultWidth: 30,
    defaultHeight: 40,
    color: '#94a3b8',
    icon: '🏠',
    resizable: true,
    description: 'Building footprint outline on site',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'borehole',
    name: 'Well / Borehole',
    category: 'site',
    defaultWidth: 2,
    defaultHeight: 2,
    color: '#0284c7',
    icon: '💧',
    resizable: false,
    description: 'Water well or borehole location',
    drawingType: 'site-plan' as DrawingType,
  },
  {
    type: 'site-road',
    name: 'Road / Street',
    category: 'site',
    defaultWidth: 30,
    defaultHeight: 20,
    color: '#6b7280',
    icon: '🛣️',
    resizable: true,
    description: 'Adjacent road or street',
    drawingType: 'site-plan' as DrawingType,
  },

  // ── Elevation View ────────────────────────────────────────────────────────
  {
    type: 'elev-wall',
    name: 'Wall Surface',
    category: 'elevation-view',
    defaultWidth: 20,
    defaultHeight: 10,
    color: '#e2e8f0',
    icon: '🧱',
    resizable: true,
    description: 'Exterior wall surface panel',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-window',
    name: 'Window (Elevation)',
    category: 'elevation-view',
    defaultWidth: 4,
    defaultHeight: 4,
    color: '#bfdbfe',
    icon: '🪟',
    resizable: true,
    description: 'Window in elevation view',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-door',
    name: 'Door (Elevation)',
    category: 'elevation-view',
    defaultWidth: 3,
    defaultHeight: 7,
    color: '#c4b5fd',
    icon: '🚪',
    resizable: true,
    description: 'Door in elevation view',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-roof-flat',
    name: 'Flat Roof',
    category: 'elevation-view',
    defaultWidth: 30,
    defaultHeight: 2,
    color: '#475569',
    icon: '▬',
    resizable: true,
    description: 'Flat roof parapet in elevation',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-roof-pitch',
    name: 'Pitched Roof',
    category: 'elevation-view',
    defaultWidth: 30,
    defaultHeight: 8,
    color: '#7c3aed',
    icon: '🔺',
    resizable: true,
    description: 'Pitched / sloped roof in elevation',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-floor',
    name: 'Floor Line',
    category: 'elevation-view',
    defaultWidth: 30,
    defaultHeight: 0.3,
    color: '#1e293b',
    icon: '━',
    resizable: true,
    description: 'Floor level line in elevation',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-ground',
    name: 'Ground Line',
    category: 'elevation-view',
    defaultWidth: 40,
    defaultHeight: 0.5,
    color: '#92400e',
    icon: '━',
    resizable: true,
    description: 'Ground / natural grade line in elevation',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-parapet',
    name: 'Parapet Wall',
    category: 'elevation-view',
    defaultWidth: 20,
    defaultHeight: 3,
    color: '#64748b',
    icon: '▬',
    resizable: true,
    description: 'Parapet wall at roof edge',
    drawingType: 'elevation' as DrawingType,
  },
  {
    type: 'elev-railing',
    name: 'Balcony Railing',
    category: 'elevation-view',
    defaultWidth: 8,
    defaultHeight: 3,
    color: '#94a3b8',
    icon: '🔧',
    resizable: true,
    description: 'Balcony or staircase railing in elevation',
    drawingType: 'elevation' as DrawingType,
  },
];

export const ITEM_CATEGORIES: Record<string, string> = {
  structure: 'Structure & Walls',
  rooms: 'Rooms',
  doors: 'Doors',
  windows: 'Windows',
  bathroom: 'Bathroom / Washroom',
  kitchen: 'Kitchen',
  bedroom: 'Bedroom Furniture',
  living: 'Living Room',
  dining: 'Dining',
  storage: 'Storage',
  outdoor: 'Outdoor / Exterior',
  stairs: 'Stairs & Corridors',
  study: 'Study & Office',
  pathway: 'Pathways & Roads',
  electrical: 'Electrical',
  plumbing: 'Plumbing',
  'structural-eng': 'Structural',
  'foundation-eng': 'Foundation',
  site: 'Site Elements',
  'elevation-view': 'Elevation View',
};

export function getItemByType(type: string): ItemDefinition | undefined {
  return ITEM_LIBRARY.find((i) => i.type === type);
}
