'use client';

import { useState } from 'react';
import { usePlannerStore } from '@/store/planner';
import { PlacedItem, RoomSummary } from '@/types';

function getRoomSummaries(items: PlacedItem[]): RoomSummary[] {
  const roomTypes = [
    'room','master-bedroom','bedroom','kids-room','guest-room',
    'living-room','drawing-room','study','prayer-room','store-room',
    'washroom','bathroom','toilet','kitchen','garage','balcony',
    'garden','patio','car-parking','landing',
  ];
  return items
    .filter((it) => roomTypes.includes(it.type))
    .map((it) => ({
      id: it.id,
      label: it.label,
      type: it.type,
      x: it.x,
      y: it.y,
      width: it.width,
      height: it.height,
      area: parseFloat((it.width * it.height).toFixed(2)),
      coordinates: {
        topLeft: { x: parseFloat(it.x.toFixed(2)), y: parseFloat(it.y.toFixed(2)) },
        topRight: { x: parseFloat((it.x + it.width).toFixed(2)), y: parseFloat(it.y.toFixed(2)) },
        bottomLeft: { x: parseFloat(it.x.toFixed(2)), y: parseFloat((it.y + it.height).toFixed(2)) },
        bottomRight: { x: parseFloat((it.x + it.width).toFixed(2)), y: parseFloat((it.y + it.height).toFixed(2)) },
      },
    }));
}

function generateReportText(store: ReturnType<typeof usePlannerStore.getState>): string {
  const { planName, planDescription, plot, items } = store;
  const rooms = getRoomSummaries(items);
  const totalArea = rooms.reduce((s, r) => s + r.area, 0);
  const now = new Date().toLocaleDateString('en-PK', { year: 'numeric', month: 'long', day: 'numeric' });

  let txt = `═══════════════════════════════════════════════════════════
HOUSE PLAN REPORT
Generated by HousePlanner · ${now}
═══════════════════════════════════════════════════════════

PLAN DETAILS
──────────────────────────────────────────────────────────
Name        : ${planName}
Description : ${planDescription || 'N/A'}

PLOT DIMENSIONS
──────────────────────────────────────────────────────────
Width       : ${plot.width} ft
Height/Depth: ${plot.height} ft
Total Area  : ${plot.width * plot.height} sq.ft  (${(plot.width * plot.height / 9).toFixed(2)} sq.yards)
Origin      : Corner ${plot.origin}

SIDES
  Side A (Top)    : ${plot.width} ft
  Side B (Right)  : ${plot.height} ft
  Side C (Bottom) : ${plot.width} ft
  Side D (Left)   : ${plot.height} ft

ROOM PLAN SUMMARY
──────────────────────────────────────────────────────────
`;

  rooms.forEach((r, i) => {
    txt += `
[${i + 1}] ${r.label}
    Type        : ${r.type}
    Dimensions  : ${r.width} ft × ${r.height} ft
    Area        : ${r.area} sq.ft
    Coordinates (from origin ${plot.origin}):
      Top-Left    : (${r.coordinates.topLeft.x}, ${r.coordinates.topLeft.y})
      Top-Right   : (${r.coordinates.topRight.x}, ${r.coordinates.topRight.y})
      Bottom-Left : (${r.coordinates.bottomLeft.x}, ${r.coordinates.bottomLeft.y})
      Bottom-Right: (${r.coordinates.bottomRight.x}, ${r.coordinates.bottomRight.y})
`;
  });

  txt += `
──────────────────────────────────────────────────────────
TOTAL BUILT-UP AREA  : ${totalArea.toFixed(2)} sq.ft

ALL PLACED ITEMS (${items.length} total)
──────────────────────────────────────────────────────────
`;

  items.forEach((it, i) => {
    txt += `${i + 1}. ${it.label} (${it.type})  |  Pos: (${it.x.toFixed(1)}, ${it.y.toFixed(1)})  |  Size: ${it.width}ft × ${it.height}ft  |  Rotation: ${it.rotation}°\n`;
  });

  txt += `
═══════════════════════════════════════════════════════════
END OF REPORT
═══════════════════════════════════════════════════════════
`;

  return txt;
}

export default function ExportModal({ onClose }: { onClose: () => void }) {
  const store = usePlannerStore();
  const [format, setFormat] = useState<'json' | 'txt' | 'csv'>('txt');

  function download(content: string, filename: string, type: string) {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleExport() {
    const safeName = store.planName.replace(/[^a-z0-9]/gi, '_').toLowerCase();

    if (format === 'json') {
      const data = {
        plan: {
          name: store.planName,
          description: store.planDescription,
          generatedAt: new Date().toISOString(),
        },
        plot: store.plot,
        rooms: getRoomSummaries(store.items),
        allItems: store.items,
      };
      download(JSON.stringify(data, null, 2), `${safeName}.json`, 'application/json');
    } else if (format === 'txt') {
      download(generateReportText(store), `${safeName}_report.txt`, 'text/plain');
    } else if (format === 'csv') {
      const headers = 'Label,Type,X (ft),Y (ft),Width (ft),Height (ft),Area (sqft),Rotation\n';
      const rows = store.items.map((it) =>
        `"${it.label}","${it.type}",${it.x.toFixed(2)},${it.y.toFixed(2)},${it.width},${it.height},${(it.width * it.height).toFixed(2)},${it.rotation}`
      ).join('\n');
      download(headers + rows, `${safeName}_items.csv`, 'text/csv');
    }
    onClose();
  }

  function handlePrint() {
    window.print();
  }

  const rooms = getRoomSummaries(store.items);
  const totalArea = rooms.reduce((s, r) => s + r.area, 0);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-slate-800 border border-slate-700 rounded-2xl p-6 w-full max-w-2xl shadow-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between mb-5">
          <h2 className="text-lg font-semibold text-white">Export Plan</h2>
          <button onClick={onClose} className="text-slate-400 hover:text-white transition">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Summary */}
        <div className="grid grid-cols-3 gap-3 mb-5">
          {[
            { label: 'Plot', value: `${store.plot.width}ft × ${store.plot.height}ft` },
            { label: 'Total Area', value: `${store.plot.width * store.plot.height} sq.ft` },
            { label: 'Items Placed', value: store.items.length },
          ].map(({ label, value }) => (
            <div key={label} className="bg-slate-700/30 rounded-xl p-3 text-center">
              <div className="text-xs text-slate-500 mb-0.5">{label}</div>
              <div className="text-sm font-semibold text-slate-200">{value}</div>
            </div>
          ))}
        </div>

        {/* Room list */}
        {rooms.length > 0 && (
          <div className="mb-5">
            <h3 className="text-sm font-medium text-slate-300 mb-2">Rooms & Spaces</h3>
            <div className="space-y-1.5 max-h-48 overflow-y-auto pr-1">
              {rooms.map((r) => (
                <div key={r.id} className="bg-slate-700/30 rounded-xl px-3 py-2 flex items-center justify-between text-sm">
                  <div className="font-medium text-slate-200">{r.label}</div>
                  <div className="flex gap-4 text-xs text-slate-400">
                    <span>{r.width}ft × {r.height}ft</span>
                    <span className="font-semibold text-slate-300">{r.area} sq.ft</span>
                    <span className="font-mono">({r.x.toFixed(1)}, {r.y.toFixed(1)})</span>
                  </div>
                </div>
              ))}
            </div>
            <div className="mt-2 text-xs text-slate-500 text-right">
              Built-up area: <span className="text-slate-300 font-semibold">{totalArea.toFixed(2)} sq.ft</span>
            </div>
          </div>
        )}

        {/* Format selector */}
        <div className="mb-5">
          <h3 className="text-sm font-medium text-slate-300 mb-2">Export Format</h3>
          <div className="grid grid-cols-3 gap-2">
            {([
              { value: 'txt', label: 'Text Report', desc: 'Human-readable document', icon: '📄' },
              { value: 'json', label: 'JSON Data', desc: 'Machine-readable data', icon: '{ }' },
              { value: 'csv', label: 'CSV Spreadsheet', desc: 'Open in Excel / Sheets', icon: '📊' },
            ] as const).map((f) => (
              <button key={f.value} onClick={() => setFormat(f.value)}
                className={`p-3 rounded-xl border text-left transition ${
                  format === f.value
                    ? 'bg-blue-600/20 border-blue-500 text-blue-300'
                    : 'bg-slate-700/30 border-slate-600 text-slate-400 hover:border-slate-500'
                }`}>
                <div className="text-lg mb-1">{f.icon}</div>
                <div className="text-sm font-medium text-slate-200">{f.label}</div>
                <div className="text-xs text-slate-500">{f.desc}</div>
              </button>
            ))}
          </div>
        </div>

        <div className="flex gap-3">
          <button onClick={handlePrint}
            className="flex-1 py-2.5 rounded-xl border border-slate-600 text-slate-300 hover:bg-slate-700 transition flex items-center justify-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print / PDF
          </button>
          <button onClick={handleExport}
            className="flex-1 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-semibold transition shadow-lg shadow-blue-600/20 flex items-center justify-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download {format.toUpperCase()}
          </button>
        </div>
      </div>
    </div>
  );
}
